#!/bin/bash

# create an environment to install all the repos
cd ..
mkdir kiboto_projects
cd kiboto_projects

# install redis
wget http://download.redis.io/redis-stable.tar.gz
tar xvzf redis-stable.tar.gz
cd redis-stable
make
cd ..

# download the repos
git clone https://github.com/circlesandlines/Kiboto.git
git clone https://github.com/circlesandlines/KibotoGameSDK.git
git clone https://github.com/circlesandlines/KibotoBotSDK.git

# install Kiboto server
cd Kiboto
pip install -r requirements.txt
cp conf/server_sample.config conf/server.config

# install bot SDK
cd ..
cd KibotoBotSDK
python setup.py install

cd ..

