#!/bin/bash


# the following is the expected directory structure:
# KibotoRecipes/start_local_demo.sh <- run here
# kiboto_projects/
# .../Kiboto
# .../KibotoClientSDK
# .../KibotoBotSDK

# stay in this directory the whole time
cd ../kiboto_projects

# start the redis server
redis-server &> redis.log &

# start the kiboto server
echo "starting kiboto server. tail outputs using: tail -f kiboto.log"
cd Kiboto
python kiboto.py &> ../kiboto.log &
cd ..

# start the sample game
echo "starting sample 'game'"
http-server KibotoGameSDK/starter_game_template.html &> game.log &

echo "wait a bit for game to initialize a session"
sleep 2

# start the sample bots
cd KibotoGameSDK
echo "starting bot sample 1, to tail outputs, use: tail -f bot_1.log"
python starter_bot_template.py &> ../bot_1.log &
echo "starting bot sample 2, to tail outputs, use: tail -f bot_2.log"
python starter_bot_template2.py &> ../bot_2.log &
cd ..

