#!/bin/bash


# the following is the expected directory structure:
# root/
# .../KibotoRecipes/start_local_demo.sh <- run here
# .../Kiboto
# .../KibotoClientSDK
# .../KibotoBotSDK

# start the redis server
redis-server

# start the kiboto server
echo "starting kiboto server. tail outputs using: tail -f kiboto.log"
python ../Kiboto/kiboto.py &> kiboto.log &

# start the sample game
excho "starting sample 'game'"
http-server ../KibotoGameSDK/ &> /dev/null &

echo "wait a bit for game to initialize a session"
sleep 2

# start the sample bots
cd ../KibotoBotSDK
echo "starting bot sample 1, to tail outputs, use: tail -f bot_1.log"
python sample_bot.py &> bot_1.log &
echo "starting bot sample 2, to tail outputs, use: tail -f bot_2.log"
python sample_bot2.py &> bot_2.log &

